# Generated by Django 3.1.3 on 2020-12-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='u',
            new_name='user',
        ),
    ]
